use_frameworks!

target 'DeviceInfo_Example' do
  pod 'DeviceInfo', :path => '../'

  target 'DeviceInfo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
